# Generated by Django 5.2.15 on 2026-08-13 05:17

import django.core.validators
import releases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0005_review_reviewevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, upload_to='report_profiles/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg')), releases.models.validate_logo_size])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['customer_name', 'project_name'],
                'constraints': [models.UniqueConstraint(fields=('customer_name', 'project_name'), name='unique_customer_project_report_profile')],
            },
        ),
    ]
